#!/bin/bash
if [[ -e /tmp/outdir/src/Display.class ]]
then
	cd /tmp/outdir/src/
	java Display $*
else
	make
	mkdir -p /tmp/outdir/src/
	cd /tmp/outdir/src/
	cp ~/andrew/MyriaStore/src/Display.java ./
	javac Display.java
	java Display $*
fi
cd -

